### ISSUE TITLE
Automatically opens another editor

### ISSUE THREAD

**Issue by yaagma** [lostfields/vscode-nodejs-repl#8] opened 2018-07-01 11:37 UTC
# Summary
When Visual Studio Code setting `"files.autoSave": "onFocusChange"` is active, the extension opens another copy of the file you were working on (when the setting is disabled, everything works ok). That setting is very useful and I'd like to be able to use it with the extensión.

# Context
`"files.autoSave": "onFocusChange"` is enabled and I  have two files open side by side (see image). I'm working on the file on the right (`z.js`):
![img1](https://user-images.githubusercontent.com/40261856/42133729-9ad9d4a8-7d2e-11e8-93a7-b21f7e6a9310.png)

# Steps to reproduce the problem
1. Type anything in the _**right panel**_ (`z.js`).
2. After that, click on the editor on the left to work on `javascript.md`. Suddenly, a new copy of `z.js` is opened in another tab covering your desired file. See image: 
![img2](https://user-images.githubusercontent.com/40261856/42133730-9af41a84-7d2e-11e8-9197-3a0afd0a9e0d.png)

So anytime you change from `z.js` to another file, _you are interrupted with a new editor that you must close_ first.

Thanks for a great extensión
Raúl
PS: Please, excuse my poor english.

**Comment by lostfields** [comment] 2018-07-30 07:33
ok, I'll try to reproduce it and find a fix.

**Comment by lostfields** [comment] 2019-03-20 19:33
I can't say that I been any good issue-solver, but at least I tried today. This may be fixed by the team of VS Code - because I can't reproduce it. Are you able to reproduce this error now?

If you are, are you running REPL for current file, eg `z.js` file?

**Comment by yaagma** [comment] 2019-03-27 13:11
The problem persists.

> If you are, are you running REPL for current file, eg z.js file?
Yes.

Mi configuration:
Version: 1.32.2 (user setup)
Commit: e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
Date: 2019-03-13T02:00:46.035Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Closed as completed** 2021-08-16 14:09 UTC
